services:
  habit_db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=habits
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: